// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PirateScaffold.Models;

#nullable disable

namespace PirateScaffold.Migrations
{
    [DbContext(typeof(PirateContext))]
    partial class PirateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("PirateScaffold.Models.Pirate", b =>
                {
                    b.Property<int>("PirateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Bounty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DevilFruit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Epithet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("PirateID");

                    b.ToTable("Pirates");
                });

            modelBuilder.Entity("PirateScaffold.Models.PirateCrew", b =>
                {
                    b.Property<int>("PirateCrewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrewName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PirateID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PirateCrewID");

                    b.HasIndex("PirateID");

                    b.ToTable("PirateCrews");
                });

            modelBuilder.Entity("PirateScaffold.Models.PirateCrew", b =>
                {
                    b.HasOne("PirateScaffold.Models.Pirate", "Pirate")
                        .WithMany("PirateCrews")
                        .HasForeignKey("PirateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pirate");
                });

            modelBuilder.Entity("PirateScaffold.Models.Pirate", b =>
                {
                    b.Navigation("PirateCrews");
                });
#pragma warning restore 612, 618
        }
    }
}
